name: Docker Image Publish
on:
  push:
    tags:        
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        registry: ghcr.io
        push: true
        tags: danielemery/solis-inverter:${{ env.TAG }}
